In [1]:
import numpy as np

In [2]:
sw = np.array([[2,2], [2,4]])
sw

array([[2, 2],
       [2, 4]])

In [3]:
(1/sw)*sw

array([[1., 1.],
       [1., 1.]])

In [4]:
inv = np.eye(2)/sw
inv

array([[0.5 , 0.  ],
       [0.  , 0.25]])

In [9]:
np.dot(sw,inv)

array([[1. , 0.5],
       [1. , 1. ]])

In [6]:
mu1 = np.array([[1], [0]])
mu2 = np.array([[-1], [-1]])
mu1-mu2

array([[2],
       [1]])

In [7]:
np.dot(inv, (mu1-mu2))

array([[1.  ],
       [0.25]])

In [11]:
np.dot(sw, np.linalg.inv(sw))

array([[ 2., -1.],
       [-1.,  2.]])